### ISSUE TITLE
LoadGenerator service fails to start

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-demo-webstore#170]
Not sure why it wasn't reported before. Maybe something wrong with my environment. 

I'm getting the following error on the start from loadgenerator service:

```
loadgenerator_1          | Traceback (most recent call last):
loadgenerator_1          |   File "/usr/local/bin/locust", line 8, in <module>
loadgenerator_1          |     sys.exit(main())
loadgenerator_1          |   File "/usr/local/lib/python3.10/site-packages/locust/main.py", line 125, in main
loadgenerator_1          |     docstring, user_classes, shape_class = load_locustfile(locustfile)
loadgenerator_1          |   File "/usr/local/lib/python3.10/site-packages/locust/main.py", line 82, in load_locustfile
loadgenerator_1          |     imported = source.load_module()
loadgenerator_1          |   File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
loadgenerator_1          |   File "<frozen importlib._bootstrap_external>", line 1063, in load_module
loadgenerator_1          |   File "<frozen importlib._bootstrap_external>", line 888, in load_module
loadgenerator_1          |   File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
loadgenerator_1          |   File "<frozen importlib._bootstrap>", line 719, in _load
loadgenerator_1          |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
loadgenerator_1          |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
loadgenerator_1          |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
loadgenerator_1          |   File "/usr/src/app/locustfile.py", line 23, in <module>
loadgenerator_1          |     from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
loadgenerator_1          |   File "/usr/local/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py", line 22, in <module>
loadgenerator_1          |     from opentelemetry.exporter.otlp.proto.grpc.exporter import (
loadgenerator_1          |   File "/usr/local/lib/python3.10/site-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py", line 39, in <module>
loadgenerator_1          |     from opentelemetry.proto.common.v1.common_pb2 import (
loadgenerator_1          |   File "/usr/local/lib/python3.10/site-packages/opentelemetry/proto/common/v1/common_pb2.py", line 36, in <module>
loadgenerator_1          |     _descriptor.FieldDescriptor(
loadgenerator_1          |   File "/usr/local/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
loadgenerator_1          |     _message.Message._CheckCalledFromGeneratedFile()
loadgenerator_1          | TypeError: Descriptors cannot not be created directly.
loadgenerator_1          | If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
loadgenerator_1          | If you cannot immediately regenerate your protos, some other possible workarounds are:
loadgenerator_1          |  1. Downgrade the protobuf package to 3.20.x or lower.
loadgenerator_1          |  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
loadgenerator_1          |
loadgenerator_1          | More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
opentelemetry-demo-webstore_loadgenerator_1 exited with code 1
```

Removing instrumentation from the `loadgenerator` solves the problem.

**Comment by cartersocha** [comment]
@mic-max, @julianocosta89, @puckpuck could one of yall take a quick look at this? I'm also having the issue locally and it breaks the app 😞

**Comment by mic-max** [comment]
Might have been related to the `requirements.in` file being removed but I wasn't easily able to find the culprit.
